// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct Sum
{
  struct Sum_vtable *vptr;
};
struct Doit
{
  struct Doit_vtable *vptr;
  int ii;
  int bb;
};
struct Test
{
  struct Test_vtable *vptr;
  int ii;
  int bb;
  int b;
  int ii;
};
// vtables structures
struct Sum_vtable
{
};

struct Doit_vtable
{
  int (*doit)();
  int (*test)();
  int (*isFalse)();
};

struct Test_vtable
{
  int (*doit)();
  int (*test)();
  int (*isFalse)();
  int (*tt)();
};


// methods
int Doit_doit(struct Doit * this, int n)
{
  int sum;
  int i;
  int a;
  int p;
  int b;

  i = 0;  sum = 0;  a = 0;  p = 0;  b = 0;  b = 0;  i = 0;  sum = 0;  a = 0;  if (0)
    a = 0;
  else
    a = 0;
  if (0)
    a = 0;
  else
    a = 0;
  return sum;
}
int Doit_test(struct Doit * this, int bbb)
{
  int rr;

  System_out_println (0);
  return 0;
}
int Doit_isFalse(struct Doit * this)
{

  return 0;
}
int Test_tt(struct Test * this, int aa, int uu)
{
  int qqq;

  qqq = 2;  System_out_println (333);
  return 1;
}

// vtables
struct Sum_vtable Sum_vtable_ = 
{
};

struct Doit_vtable Doit_vtable_ = 
{
  Doit_doit,
  Doit_test,
  Doit_isFalse,
};

struct Test_vtable Test_vtable_ = 
{
  Doit_doit,
  Doit_test,
  Doit_isFalse,
  Test_tt,
};


// main method
int Tiger_main ()
{
  struct Doit * x_0;
  System_out_println ((x_0=((struct Doit*)(Tiger_new (&Doit_vtable_, sizeof(struct Doit)))), x_0->vptr->doit(x_0, 101)));
}




